"use client";

import { useCallback, useState } from "react";
import type { AttributionReceipt } from "@lineage/shared";

import { useLineage } from "@/hooks/useLineage";

// The seed manifest is generated by `pnpm seed:testnet` at the repo root and
// pinned into source control alongside `deployments.json`. We import it
// statically so DEMO_AGENTS is bound to the real on-chain token ids that
// match the current testnet deployment.
//
// If the import fails at runtime (e.g. the file was deleted between
// `seed:testnet` runs), we fall back to a single placeholder agent so the
// rest of the demo UI still renders. The placeholder uses sentinel id 0n
// — runInference against id 0 will fail loudly, which is the correct UX
// signal that the seed manifest is missing.
import seedOutput from "../../../../../scripts/seed-output.json";

/**
 * Demo state machine.
 *
 *   idle        — nothing in flight; user can click "Run inference".
 *   compute     — POST /api/inference dispatched, awaiting 0G Compute.
 *   attestation — fake sub-phase: TEE attestation is being fetched server-side.
 *   persisting  — fake sub-phase: receipt is being written to 0G Storage.
 *   settling    — POST /api/settle dispatched, awaiting RoyaltySplitter.postBatch.
 *   done        — last action succeeded; receipt and/or payouts populated.
 *
 * The server endpoint is opaque (one POST → one JSON response) so the three
 * `run`-phase substates are advanced on a timer purely for UX feedback.
 */
export type DemoStatus =
  | "idle"
  | "compute"
  | "attestation"
  | "persisting"
  | "settling"
  | "done";

export interface AgentSpec {
  id: string;
  name: string;
  description?: string;
  modelTokenId: bigint;
  skills: bigint[];
  data: bigint[];
  memory: bigint[];
}

interface SeedAgent {
  id: string;
  name: string;
  description?: string;
  modelTokenId: string;
  skills: string[];
  data: string[];
  memory: string[];
}

interface SeedOutputShape {
  agents: SeedAgent[];
}

const PLACEHOLDER_AGENT: AgentSpec = {
  id: "news-summarizer",
  name: "News Summarizer (placeholder — run `pnpm seed:testnet`)",
  description: "Summarises news articles using a web-search skill.",
  modelTokenId: 0n,
  skills: [],
  data: [],
  memory: [],
};

function toBig(s: string): bigint {
  return BigInt(s);
}

function buildDemoAgents(): AgentSpec[] {
  try {
    const seed = seedOutput as SeedOutputShape | undefined;
    if (!seed || !Array.isArray(seed.agents) || seed.agents.length === 0) {
      console.warn(
        "seed-output.json missing, falling back to placeholder DEMO_AGENTS",
      );
      return [PLACEHOLDER_AGENT];
    }
    return seed.agents.map((a) => ({
      id: a.id,
      name: a.name,
      ...(a.description !== undefined ? { description: a.description } : {}),
      modelTokenId: toBig(a.modelTokenId),
      skills: a.skills.map(toBig),
      data: a.data.map(toBig),
      memory: a.memory.map(toBig),
    }));
  } catch (err) {
    console.warn(
      "seed-output.json missing, falling back to placeholder DEMO_AGENTS",
      err,
    );
    return [PLACEHOLDER_AGENT];
  }
}

export const DEMO_AGENTS: AgentSpec[] = buildDemoAgents();

/**
 * A single per-recipient row in the Payouts card.
 *
 * After the /api/settle refactor:
 *   - `recipient` is a real on-chain address (lower-cased), not a synthetic
 *     "data-7" label.
 *   - `amount` is a wei-denominated bigint serialised as a string — the
 *     frontend renders it via formatEther.
 *   - `proof` is the Merkle proof for this payout (also persisted server-side
 *     so the recipient can claim from /earnings later).
 *   - `batchId` / `txHash` link the payout back to the on-chain batch tx.
 *
 * `weight` is kept as a float in [0, 1] purely for the display micro-bar.
 */
export interface PayoutRow {
  recipient: string;
  label: string;
  /** Wei amount as a decimal string. Use formatEther at render time. */
  amount: string;
  weight: number;
  proof: `0x${string}`[];
  batchId: string;
  txHash: `0x${string}`;
}

/**
 * Pointer returned by the receipt-sink (0G Storage / 0G DA). We surface it on
 * the demo screen so the VerificationPanel can render the on-chain storage
 * root that anchors the persisted receipt.
 */
export interface DemoDaPointer {
  commitment: `0x${string}`;
  blobIndex: number;
}

interface ApiInferenceResponse {
  output: string;
  receipt: AttributionReceipt;
  daPointer: DemoDaPointer;
}

export interface DemoSettleResult {
  batchId: string;
  txHash: `0x${string}`;
  merkleRoot: `0x${string}`;
}

interface ApiSettleResponse {
  batchId: string;
  txHash: `0x${string}`;
  merkleRoot: `0x${string}`;
  payouts: Array<{
    recipient: `0x${string}`;
    token: `0x${string}`;
    amount: string;
    proof: `0x${string}`[];
  }>;
}

export function useDemoScreen() {
  const { account, isReady } = useLineage();
  const [status, setStatus] = useState<DemoStatus>("idle");
  const [error, setError] = useState<string | null>(null);
  const [agent, setAgent] = useState<AgentSpec>(DEMO_AGENTS[0]!);
  const [prompt, setPrompt] = useState<string>(
    "Summarize today's top story about AI.",
  );
  const [receipt, setReceipt] = useState<AttributionReceipt | null>(null);
  const [output, setOutput] = useState<string | null>(null);
  const [payouts, setPayouts] = useState<PayoutRow[]>([]);
  const [settleTxHash, setSettleTxHash] = useState<`0x${string}` | null>(null);
  const [daPointer, setDaPointer] = useState<DemoDaPointer | null>(null);
  const [settleResult, setSettleResult] = useState<DemoSettleResult | null>(
    null,
  );

  const reset = useCallback(() => {
    setStatus("idle");
    setError(null);
    setReceipt(null);
    setOutput(null);
    setPayouts([]);
    setSettleTxHash(null);
    setDaPointer(null);
    setSettleResult(null);
  }, []);

  const run = useCallback(async () => {
    if (!isReady || !account) {
      setError("Wallet not ready — connect on chainId 16602 first");
      return;
    }
    setError(null);
    setReceipt(null);
    setPayouts([]);
    setOutput(null);
    setSettleTxHash(null);
    setDaPointer(null);
    setSettleResult(null);
    setStatus("compute");

    // The /api/inference call is one opaque POST; advance phase indicator on
    // a timer purely for UX. We clear the timer on response (success or error).
    let phaseStep = 0;
    const phases: DemoStatus[] = ["attestation", "persisting"];
    const phaseTimer = setInterval(() => {
      const next = phases[phaseStep++];
      if (next) setStatus(next);
      else clearInterval(phaseTimer);
    }, 3000);

    try {
      const res = await fetch("/api/inference", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          modelTokenId: agent.modelTokenId.toString(),
          skills: agent.skills.map((s) => s.toString()),
          data: agent.data.map((d) => d.toString()),
          memory: agent.memory.map((m) => m.toString()),
          prompt,
          agentAddress: account,
        }),
      });
      const payload = (await res.json()) as
        | ApiInferenceResponse
        | { error: string; kind?: string };
      if (!res.ok || "error" in payload) {
        const msg =
          "error" in payload && payload.error
            ? payload.error
            : `inference failed (HTTP ${res.status})`;
        throw new Error(msg);
      }
      setReceipt(payload.receipt);
      setOutput(payload.output);
      setDaPointer(payload.daPointer);
      setStatus("done");
    } catch (err) {
      console.error("inference failed", err);
      setError(err instanceof Error ? err.message : String(err));
      setStatus("idle");
    } finally {
      clearInterval(phaseTimer);
    }
  }, [account, isReady, agent, prompt]);

  const settle = useCallback(async () => {
    if (!receipt) return;
    setError(null);
    setStatus("settling");
    try {
      const res = await fetch("/api/settle", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ receipt }),
      });
      const payload = (await res.json()) as
        | ApiSettleResponse
        | { error: string };
      if (!res.ok || "error" in payload) {
        const msg =
          "error" in payload && payload.error
            ? payload.error
            : `settle failed (HTTP ${res.status})`;
        throw new Error(msg);
      }

      // Aggregate the receipt's per-token weights so the row's `weight`
      // micro-bar still has a useful 0..1 value. Weights aren't 1:1 with
      // payouts (multiple tokens may share an owner) but it's good enough
      // for the display bar.
      const weightByRecipient = new Map<string, number>();
      // We don't know recipient→token mapping client-side; fall back to
      // distributing each payout's weight as `amount / totalAmount` which is
      // monotonically equivalent for the display bar.
      const total = payload.payouts.reduce(
        (acc, p) => acc + BigInt(p.amount),
        0n,
      );

      const rows: PayoutRow[] = payload.payouts.map((p) => {
        const weight =
          total === 0n ? 0 : Number((BigInt(p.amount) * 10_000n) / total) / 10_000;
        const lower = p.recipient.toLowerCase();
        weightByRecipient.set(lower, weight);
        return {
          recipient: p.recipient,
          label: `${p.recipient.slice(0, 6)}…${p.recipient.slice(-4)}`,
          amount: p.amount,
          weight,
          proof: p.proof,
          batchId: payload.batchId,
          txHash: payload.txHash,
        };
      });
      setPayouts(rows);
      setSettleTxHash(payload.txHash);
      setSettleResult({
        batchId: payload.batchId,
        txHash: payload.txHash,
        merkleRoot: payload.merkleRoot,
      });
      setStatus("done");
    } catch (err) {
      console.error("settle failed", err);
      setError(err instanceof Error ? err.message : String(err));
      setStatus("idle");
    }
  }, [receipt]);

  return {
    status,
    error,
    agent,
    setAgent,
    prompt,
    setPrompt,
    receipt,
    output,
    payouts,
    settleTxHash,
    daPointer,
    settleResult,
    run,
    settle,
    reset,
  };
}
